
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: #clientID
            clientSecret: #clientSecret
          google:
            client-id: #clientID
            client-secret: #clientSecret
            